# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 05:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_auto_20190724_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
